### ISSUE TITLE
Duplicate Strategies

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/Axelrod#138] opened 2015-04-01 07:10 UTC
As more strategies are created, it becomes more difficult to spot when a new strategy is a duplication of an existing one. Simple source code comparison is no good as there are many different ways to code a given strategy.

Instead, we could:
- Create a set of players whose strategies are entirely deterministic and do not depend on the opponent in any way (e.g. Cooperator, Defector, 'Cooperate for 5 turn, defect for 3 and then cooperate until the end'
- Run a tournament with those players plus a single strategy under test only
- Record the score of the single strategy somewhere permanently
- Do the above for all existing strategies
- For any new strategy, run the tournament above. If the score matches any existing, have a look at the code for those and judge whether the strategy is indeed a duplicate (or whether a new 'test' strategy could be written to differentiate between them)

**Comment by drvinceknight** [comment] 2015-04-01 07:13
Yup, I think that sounds good, as I said on gitter this only flags and we'd still need to take a look. Really like the idea. 

This could be added to the test suite right? So if the tests pass we know the strategy is different, if the test fails:

1. We look through the code and conclude that it is the same.
2. We look through the code and conclude that a new strategy should be added to the test suite to differentiate.

Yeah this would be awesome...

**Comment by meatballs** [comment] 2015-04-01 07:15
This just narrows down the list to check a new strategy against. It's not intended to give a definitive answer.

I suppose I came up with it because several new strategies have come in whilst I've been doing 'infrastructure' stuff and I have no idea how they work. I'd have no clue whether any new strategy was similar to those already!

**Comment by drvinceknight** [comment] 2015-04-01 07:17
> This just narrows down the list to check a new strategy against. It's not intended to give a definitive answer.

Yup. I love the idea of adding them to the test suite and so failing `_is_a_new_strategy` is something that can be fixed by modifying the tests by adding a new strategy to the test tournament :)

Or perhaps giving the potential for the strategy to be flagged as `new=True` which means it does not need to go through the test tournament. I am just thinking that perhaps there will be some strategies that act in a particular way which makes them hard to differentiate but that we KNOW are different (so that label would overide).

**Comment by drvinceknight** [comment] 2015-04-01 07:32
This will need to be documented with an example I think...

**Comment by meatballs** [comment] 2015-04-01 11:25
I suspect there might be clever mathematical / statistical jiggery-pokery that could be done in order to calculate degrees of similarity from the results. Now if only I could think of how to lay my hands on the sorts of people who might know how to do that.......

**Comment by drvinceknight** [comment] 2015-04-01 11:29
If only... That would be a very cool problem to look at. Let's talk about
it.

**Comment by meatballs** [comment] 2015-04-19 12:00
I'm putting this back on to the backlog. I'm busy getting the basics of djaxelrod up and running at the moment and this isn't really in progress at all. 

I'm more than happy to pick it up later and equally happy if anyone else wants a crack at it.

**Comment by drvinceknight** [comment] 2015-04-19 13:43
It's something I'd certainly like to take a look at at some point but the
next couple of weeks are going to be a bit crazy so it'll be a while.

**Comment by marcharper** [comment] 2015-05-07 16:08
If a strategy is memory-one, then one just has to check the plays for the empty history and for CC, CD, DC, and DD (say test each history 1000 times and compute the four-vector). So any two players matching behavior on all five histories are identical. Similarly for memory-two players like Tit-for-two-tats, you'd need to check [C,D]^3 (or maybe [C,D]^4), and so on. I don't think you can really do much better than this for definitive duplicate detection.

This relies on honest memoryone tagging... a strategy could pretend to be memory one for a short period of time to pass the test and then change its strategy. We actually implemented a structure to infer a strategy's four-vector (and determine if it started deviating from it) for [this paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0120625).

Some of the strategies are "memory-infinity", like Grudger, since it has an internal memory that may take arbitrarily many rounds to alter (depending on opponent), or Forgetful-Fool-Me-Once, since it has a small probability of randomly forgetting its memory. For such strategies it could be very difficult to tell the difference between two similar strategies, i.e. requiring thousands of rounds of play (or more)  before a statistical signal suggests that they are different.

**Comment by drvinceknight** [comment] 2015-05-07 17:34
I was discussing this with a colleague today. It's a very neat statistical
problem and we have a couple of ideas as to finding that statistical
signal. The problem is one of finding the smallest set of strategies that
can be used as a test bed. I'm hoping to tinker with some sort of principal
component analysis (which does not directly apply...)...

**Comment by marcharper** [comment] 2015-05-07 18:00
My co-author Chris Lee at UCLA had some ideas on this, you might like talking with him. One should be able to detect statistically if a player can be accurately modelled as memory-one, memory-two, etc. It's something we considered adding to the IP_0 strategy in the paper I linked above.

**Comment by marcharper** [comment] 2015-10-13 22:20
Re #360, let's try to point out, in the docs and/or docstrings, when the parameterized strategies have special cases that are otherwise implemented. For example, Random(0) and Random(1) are Defector and Cooperator, respectively.

**Comment by drvinceknight** [comment] 2015-10-14 06:57
:+1:

**Comment by marcharper** [comment] 2015-10-27 17:49
So one thing we could do on this front -- run the tests of one strategy on another. If they pass, perhaps they are the same. If they fail, the two strategies are definitely different. However right now this causes test failures because of the name / classifier classes and the manner in which unittest runs tests.

**Comment by drvinceknight** [comment] 2016-05-16 17:17
In one of the papers @marcharper circulated they mention something called the fingerprint of a strategy which is specifically designed with this purpose in mind: http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=1688322&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D1688322

We should implement the fingerprints :) (That paper has some links to other papers specific to this). Could be a job for my Summer student.

**Comment by marcharper** [comment] 2016-05-16 19:46
It's definitely worth looking into.

**Comment by alcarney** [comment] 2016-09-19 16:37
[Here](https://github.com/alcarney/axelrod-fingerprints/blob/master/fingerprints.ipynb) is my attempt from the sprint at the recent PyConUK to make progress towards implementing strategy fingerprints. - Unfortunately I had trouble reproducing some of the results from the thesis I was using as reference (which is linked in the notebook)

**Comment by marcharper** [comment] 2016-12-04 19:33
Worth a revisit now?

**Comment by drvinceknight** [comment] 2016-12-04 19:37
> Worth a revisit now?

Yup. @theref will be looking in to this as part of his project, mainly starting properly in the new year as part of his project (which will take a backseat for a bit as is exams come up), if we're happy to move in time with that it would be great (from his project's point of view) to leave this with that.

**Comment by meatballs** [comment] 2017-12-08 14:21
Can we close this one now?

**Comment by drvinceknight** [comment] 2017-12-08 15:07
I'm happy to, the fingerprints give us the ability to check any given pair and the work @theref did gives us the ability to check more. I've got writing that (@theref's work) as a paper and exposing it a bit more (it involves training models etc which will need to be updated etc...) on my to do list so we might prefer to leave this issue open until I've done that? (But I'm also perfectly happy to close the issue, either way I'll be writing the paper as soon as I get a chance - it's on my list! :))

**Comment by drvinceknight** [comment] 2017-12-08 15:07
(I'm going with closing, feel free to reopen :+1:)

**Closed by drvinceknight** 2017-12-08 15:07 UTC
Labels: enhancement
